name: HerpDerpPartyPack
version: 1.0
main: andrewome.herpderppartypack.HerpDerpPartyPack

commands:
  helmetsOn:
    description: Make everyone put on their golden helmets. Will be removed after a specified time.
    usage: /<command>
  seeker:
    description: Equip your player with items required for seekers
    usage: /<command>
  hider:
    description: Equip your player with items required for hiders
    usage: /<command>
  start_zombie:
    description: Starts zombie infection!
    usage: /<command>
  stop_zombie:
    description: Forcefully stops zombie infection.
    usage: /<command>
  start_hns:
    description: Starts hide and seek
    usage: /<command>
  stop_hns:
    description: Forcefully stops hide and seek.
    usage: /<command>
  start_ctf:
    description: Starts CTF
    usage: /<command>
  stop_ctf:
    description: Forcefully stops CTF
    usage: /<command>
  shift:
    description: Shift player to opposing team
    usage: /<command> player_name